### PR TITLE
Mention of listening to map events

### PR DESCRIPTION
**Pull request by hdrodel**
Added a small section mentioning the option to listen for map events on the GoogleMap component

### CODE REVIEW

**Comment by HusamElbashir** [comment]
Thanks for the contribution @hdrodel. I say this probably belongs in this section since there is already mention of `MapOptions` so we just need to add the events:
https://github.com/inocan-group/vue3-google-map/blob/develop/docs/getting-started/index.md#your-first-map 
I'd also update the relevant section in the readme:
https://github.com/inocan-group/vue3-google-map/blob/develop/README.md#your-first-map

**Comment by hdrodel** [comment]
Want me to update the pull request or do you want to add it?

**Comment by HusamElbashir** [comment]
If you could update the PR that'd be great

**Comment by hdrodel** [comment]
Ok @HusamElbashir  i have updated my pull request

**Review by HusamElbashir — APPROVED** [review]
Perfect. Thanks again for the contribution!

**Pull request merged**
