### PR TITLE
#203 Add support for nonce to be used to pass to js-api-loader

### PR DESCRIPTION
**Pull request by Diogomrol**
All the context on the issue #203 

Adding support to receive a prop with nonce that can then be passed to js-api-loader.

Thank you for your time 👍

### CODE REVIEW

**Comment by Diogomrol** [comment]
@HusamIbrahim tagging you here for visibiliy on this :)

**Comment by HusamIbrahim** [comment]
Thanks for your contribution @Diogomrol!

**Comment by Diogomrol** [comment]
Ty very much @HusamIbrahim :) Do we need to do anything to make a new release from this? Thought it would trigger automatically but doesn't look like it did

**Comment by HusamIbrahim** [comment]
Our pipeline triggers on merging to main not develop.

You should be able to find a new release now `v0.20.0`

**Comment by mbrodala** [comment]
So to get this right: one can use `<google-map ... :nonce="some.prop">` to inject a nonce into the maps loading process?

I tried that and can see my `nonce` set as property on `GoogleMap` in the Vue Dev Tools inspector. Still there are no styles and I get this:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.googleapis.com ... 'nonce-/IwaTDQ+iJC9xieQ7tBkGw==' 'unsafe-inline' 'nonce-df1a0814a5f7685aacdd71b5845383f7'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Related code in the compiled Webpack bundle:

```javascript
!function() {
            try {
                if (typeof document < "u") {
                    var e = document.createElement("style");
                    e.appendChild(document.createTextNode(".mapdiv[data-v-d05fc6bc]{width:100%;height:100%}.custom-control-wrapper[data-v-d099a3a6]{display:none}.mapdiv .custom-control-wrapper[data-v-d099a3a6]{display:inline-block}.info-window-wrapper[data-v-cbe1707b]{display:none}.mapdiv .info-window-wrapper[data-v-cbe1707b]{display:inline-block}.custom-marker-wrapper[data-v-2d2d343a]{display:none}.mapdiv .custom-marker-wrapper[data-v-2d2d343a]{display:inline-block}")),
                    document.head.appendChild(e)
                }
            } catch (e) {
                console.error("vite-plugin-css-injected-by-js", e)
            }
        }();
```

Am I missing something?

**Pull request merged**
