### PR TITLE
Add vModel to infoWindow

### PR DESCRIPTION
**Pull request by Tofandel**
This would solve #143

Disclaimer: this has not been tested, so do not merge yet

### CODE REVIEW

**Comment by HusamIbrahim** [comment]
If we add this feature I'd like it to use an explicit `v-model:open`. That way it isn't ambiguous and we could have others added as well in the future such as `v-model:content` etc.

**Comment by randomnessdev** [comment]
Will this branch be merged ?

**Comment by HusamIbrahim** [comment]
@Tofandel Fair enough do let me know when you think this is ready

**Comment by yankeeinlondon** [comment]
Thanks @Tofandel; going forward can you get in the habit of signing all commits? It's a good practice and dead simple once you invest the initial "and how do I do that" effort :)

**Comment by Tofandel** [comment]
@yankeeinlondon I was still testing out the PR, there is one type issues that will likely prevent the build

**Comment by yankeeinlondon** [comment]
Ok @Tofandel ; sorry I jumped the gun there ... multitasking (poorly)

**Comment by Tofandel** [comment]
Okay, I finished testing, the good news is it was working, so only the missing type was the issue, I also added "prepare" to the scripts so that the package could be installed from git

**Comment by HusamIbrahim** [comment]
@Tofandel Sorry for the mishap. Can you open a new PR and link this one to preserve the conversation history?

**Comment by Tofandel** [comment]
Sure will do, but now that it's rebased on master, there was a recent `fastdom` addition which is not in the dependencies of the lib

**Pull request merged**
